---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---
Title: Cloud-based mass processing of structured global geo-datasets in R: A case study of the World Database on Protected Areas and conservation related geo-variables

The webpage contains results from the hundreds of simulations obtained after processing several datasets. 

## Chapters

### Raster benchmarks (core functions)

- [01 terraZonal vs terraExtract vs exactExtractr  (WDPA)](01_zonal_vs_extract_vs_exactextractr_WDPA.html)

- [02 terraZonal vs terraExtract vs exactExtractr  (Fishnets)](02_zonal_vs_extract_vs_exactextractr_Fishnets.html)

- [03 sequential vs parallelization (WDPA)](03_sequential_vs_parallelization_WDPA.html)

- [04 sequential vs parallelization (Fishnets)](04_sequential_vs_parallelization_Fishnets.html)

### Package mapme.biodiversity functions

- [05 vector benchmarks (mapme.biodiversity)](05_vector_benchmarks.html)

- [06 raster benchmarks (mapme.biodiversity)](06_raster_benchmarks.html)
