---
title: "benchmark - raster operations"
author: "Om Prakash Bhandari"
date: "28/03/2022"
output: html_document
---

#### Polygons - area of interest (aoi)

1. wdpa polygons (7495)
2. simplified wdpa polygons (4722)
3. fishnet gridded cells (216425)

Let's see how these three different aoi polygons look like:

```{r leafletdata, message=FALSE, warning=FALSE, include=FALSE}

library("sf")
library("terra")
library("leaflet")
library("exactextractr")
library("tidyverse")
library("tidyr")
library("ggplot2")
library("leaflet")
library("leaflet.extras")
library("leaflet.extras2")
library("ggsci")
library("scales")
library("htmltools")
library("RColorBrewer")
library("plotly")
library("rmarkdown")
library("magrittr")

# load WDPA polygon
pa.sf <- read_sf("../../datalake/mapme.protectedareas/input/wdpa_kfw/wdpa_kfw_spatial_latinamerica_2021-04-22_allPAs_valid.gpkg")
pa.sf <- st_transform(pa.sf, 4326)

# load simplified WDPA polygon
spa.sf <- read_sf("../../datalake/mapme.protectedareas/input/wdpa_kfw/wdpa_kfw_spatial_latinamerica_2021-04-22_allPAs_valid_simplified.gpkg")
spa.sf <- st_transform(spa.sf, 4326)

# load fishnet polygons
fishnet.sf <- read_sf("../../datalake/mapme.protectedareas/processing/fishnet/honeycomb_5_sqkm_kfw.gpkg")
fishnet.sf <- st_transform(fishnet.sf, 4326)


# subset data for only map
pa_map <- pa.sf %>%
  dplyr::filter(ISO3 %in% "DOM")
spa_map <- spa.sf %>%
  dplyr::filter(ISO3 %in% "DOM")
fish_map <- st_crop(fishnet.sf, pa_map)
# visualize
my_map <-
  leaflet() %>%
  addTiles(group = "OpenStreetMap") %>%
  addProviderTiles(providers$CartoDB.Positron, group="CartoDB") %>%
  addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%
  addPolygons(data = pa_map,opacity = 0.9,color = "orange", group = "WDPA polygons",label = ~htmlEscape(WDPAID),weight = 1)%>%
  addPolygons(data = spa_map,opacity = 1,color = "green", group = "Simplified WDPA polygons",label = ~htmlEscape(WDPAID),weight = 1)%>%
  addPolygons(data = fish_map,opacity = 1,color = "blue", group = "Fishnets",label = ~htmlEscape(poly_id),weight = 1)%>%
  addFullscreenControl() %>%
  addLayersControl(
    baseGroups = c("CartoDB", "Satellite"),
    overlayGroups = c("WDPA polygons","Simplified WDPA polygons","Fishnets"),
    options = layersControlOptions(collapsed = FALSE))

```

```{r map, message=FALSE, warning=FALSE, include=TRUE}

my_map
```


```{r wdpa, message=FALSE, warning=FALSE, include=FALSE}

# WDPA POLYGONS
# load pop raster and crop
pop <- rast("../../datalake/mapme.protectedareas/input/world_pop/global_mosaic2020.tif")
pop_crop <- crop(pop, pa.sf)

# terra::extract
t1 <- Sys.time()
pa.v <- vect(pa.sf)
terra_extract <- terra::extract(pop_crop, pa.v, 'mean', na.rm = T)
t2 <- Sys.time()
dt_te <- as.numeric(t2-t1, units="secs")

# terra::zonal
t1 <- Sys.time()
pa.v <- vect(pa.sf)
mask <- terra::mask(pop_crop, pa.v)
rasterize <- terra::rasterize(pa.v, mask, "WDPA_PID")
terra_zonal <- terra::zonal(mask, rasterize, 'mean', na.rm = T)
t2 <- Sys.time()
dt_tz <- as.numeric(t2-t1, units="secs")

# exact extract
t1 <- Sys.time()
exact_extract <- exact_extract(pop_crop, pa.sf, 'mean')
t2 <- Sys.time()
dt_ee <- as.numeric(t2-t1, units="secs")
```


```{r simplified_wdpa, message=FALSE, warning=FALSE, include=FALSE}

# SIMPLIFIED WDPA POLYGONS
# crop raster
pop_crop <- crop(pop, spa.sf)

# terra::extract
t1 <- Sys.time()
spa.v <- vect(spa.sf)
terra_extract <- terra::extract(pop_crop, spa.v, 'mean', na.rm = T)
t2 <- Sys.time()
dts_te <- as.numeric(t2-t1, units="secs")

# terra::zonal
t1 <- Sys.time()
spa.v <- vect(spa.sf)
mask <- terra::mask(pop_crop, spa.v)
rasterize <- terra::rasterize(spa.v, mask, "WDPA_PID")
terra_zonal <- terra::zonal(mask, rasterize, 'mean', na.rm = T)
t2 <- Sys.time()
dts_tz <- as.numeric(t2-t1, units="secs")

# exact extract
t1 <- Sys.time()
exact_extract <- exact_extract(pop_crop, spa.sf, 'mean')
t2 <- Sys.time()
dts_ee <- as.numeric(t2-t1, units="secs")
```


```{r fishnet, message=FALSE, warning=FALSE, include=FALSE}

# FISHNET POLYGONS (grid cells)
# crop raster
pop_crop <- crop(pop, fishnet.sf)

# terra::extract
t1 <- Sys.time()
fishnet.v <- vect(fishnet.sf)
terra_extract <- terra::extract(pop_crop, fishnet.v, 'mean', na.rm = T)
t2 <- Sys.time()
dtfs_te <- as.numeric(t2-t1, units="secs")

# terra::zonal
t1 <- Sys.time()
fishnet.v <- vect(fishnet.sf)
mask <- terra::mask(pop_crop, fishnet.v)
rasterize <- terra::rasterize(fishnet.v, mask, "poly_id")
terra_zonal <- terra::zonal(mask, rasterize, 'mean', na.rm = T)
t2 <- Sys.time()
dtfs_tz <- as.numeric(t2-t1, units="secs")

# exact extract
t1 <- Sys.time()
exact_extract <- exact_extract(pop_crop, fishnet.sf, 'mean')
t2 <- Sys.time()
dtfs_ee <- as.numeric(t2-t1, units="secs")
```

#### Time taken to compute statistics using terra-zonal, terra-extract and exact-extract

```{r plot, message=FALSE, warning=FALSE, include=FALSE}

df.result <- data.frame(Functions = c("terra::extract", "terra::zonal", "exact_extract"),
                        WDPA = c(dt_te, dt_tz, dt_ee),
                        Simplified_WDPA = c(dts_te, dts_tz, dts_ee),
                        Fishnet = c(dtfs_te, dtfs_tz, dtfs_ee))
df.result.long <- pivot_longer(df.result,
                               cols = c("WDPA", "Simplified_WDPA", "Fishnet"))
result.plot <- ggplot(data = df.result.long, aes(x=name, y=value, fill=Functions)) + 
  geom_col(position = 'dodge') +
  xlab('Type of Polygons') +
  ylab('Time elapsed (s)') +
  ggtitle('comparison of time taken by three different functions to compute raster statistics')
```

```{r plot2, message=FALSE, warning=FALSE, include = TRUE, fig.width = 12}

result.plot
```
